name: Angular Scaffold

on:
  push:
    branches:
      - init-branch

jobs:
  scaffold:
    runs-on: ubuntu-latest

    steps:
    - name: Path
      run: |
       pwd       
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.13'

    - name: Install Angular CLI
      run: npm install -g @angular/cli    
      
    - name: Configure Git and Push Changes
      run: |
        git config user.email "paccarini.bar@outlook.com"
        git config user.name "P4dr4"
        git checkout -b main

    - name: Scaffold Angular Application
      run: |
        npm install -g @angular/cli
        ng new portfolio --minimal --skip-git --skip-tests
        cd portfolio
        ng generate component home
        cd ..
        pwd
        git push origin main
        git add .
        git commit -m "Scaffolded Angular component"
        git pull origin main
